Task_1_2_1
TheBlek/OOP pull request #5
Opened 2023-10-12 03:33 UTC by TheBlek

2023-10-13 12:42 UTC, TheBlek commented
Sorry for early review request

2023-10-16 10:38 UTC, shadrina requested changes

2023-10-16 10:38 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +    private boolean isBFS;
Почему выбрана такая последдовательность членов класса? Из соображений сначала показать контракт?

2023-10-16 10:38 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +    private boolean isBFS;
Давай enum с двумя константами.

2023-10-16 10:38 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +        private class SearchState<T> {
Он как-то намешан с полями, reviewdog не зря ругается

2023-10-16 10:38 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +            assert(!searchStack.isEmpty());
`assert` это не метод, это ключевое слово, которое задает отдельную синтаксическую конструкцию.

```
assert expression : errorMessage;
```

2023-10-16 10:38 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +            public int CurrentChild;
Тут тоже обсуждали, не Java-style

2023-10-16 10:38 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +    private boolean modified;
А если я возьму несколько итераторов? 
Проблема здесь в том, что у тебя операция взятия итератора -- это модифицирующая операция, она меняет состояние.

```
for (var node: tree) {
    tree.addChild(child);
    tree.iterator()
    // OK
}
```

2023-10-16 13:19 UTC, TheBlek commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +    private boolean isBFS;
Да, решил поэкспериментировать с расположением полей. Видел мнение, что в таком виде код читается легче как раз из-за того, что приватные поля показываем в последнюю очередь - они скорее всего не нужны читающему.

2023-10-17 07:28 UTC, shadrina requested changes

2023-10-17 07:28 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +            default -> throw new IllegalStateException("Invalid iteration order: " + order);
Эта ветка невозможна. Перечисления на то и нужны, чтобы знать в момент компиляции все возможные константы. А ты их знаешь -- это либо Bfs, либо Dfs

2023-10-17 07:28 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +            if (root.hashCode() != initHash) {
С таким подходом ты можешь не заметить изменение, которое было. Равный hashCode не гарантирует равенство объектов.

2023-10-17 07:28 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +            root = tree;
Это необязательно хранить, это внутренний класс, у тебя есть `Tree.this`. Это оно и есть.

2023-10-17 07:28 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +        private class SearchState<T> {
Вот тут кажется, что класс можно сделать `static`

2023-10-17 07:28 UTC, shadrina commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +        return this.value == otherTree.value && this.children.equals(otherTree.children);
Структурно разные деревья ошибочно будут равны

2023-10-17 07:49 UTC, TheBlek commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +            if (root.hashCode() != initHash) {
Да, могу не заметить изменение, которое было. Но если сохранять только modCount верхнего, то "незаметится" ещё больше изменений. Я про это все написал в документации к iterator. 
И вроде бы вы сказали на паре, что можно сделать и так, только надо в доке написать

2023-10-17 07:53 UTC, TheBlek commented on Task_1_2_1/src/main/java/ru.nsu.kuklin.tree/Tree.java
> +        return this.value == otherTree.value && this.children.equals(otherTree.children);
Почему? Дети тут сравниваются по определенному мной equals, то есть они сравниваются полностью. Тут проблема в другом: будут не равны деревья с разным порядком добавления одних и тех же элементов

2023-10-28 10:00 UTC, shadrina approved these changes

2023-10-28 11:49 UTC, merged