Task_1_4_1
TheBlek/OOP pull request #8
Opened 2023-11-20 01:34 UTC by TheBlek

2023-11-28 08:15 UTC, shadrina requested changes

2023-11-28 08:15 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kuklin/gradebook/GradeBook.java
> +}
Давай еще `toString`

2023-11-28 08:15 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kuklin/gradebook/GradeBook.java
> +}
Чтобы выводил оценки соответствующей строкой (неуд, удовл и тд)

2023-11-28 08:15 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kuklin/gradebook/GradeBook.java
> +public class GradeBook {
Как-то учитываются пересдачи? Потеря стипендии в случае пересдачи?

2023-11-28 09:06 UTC, TheBlek commented on Task_1_4_1/src/main/java/ru/nsu/kuklin/gradebook/GradeBook.java
> +public class GradeBook {
Да, учитывается. Если оценка передачей получена, то стипендии не будет

2023-12-05 04:03 UTC, shadrina approved these changes

2023-12-05 04:03 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/kuklin/gradebook/GradeBook.java
> +}
Ну я, конечно, имела в виду строку, которая отличается от имени enum'а)
В принципе на Approve достаточно

2023-12-05 04:04 UTC, merged